spring.application.name=finguard

# =========================================================
# SERVER
# =========================================================

# Render provides PORT in production.
# 8080 is used when running locally.
server.port=${PORT:8080}


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


# =========================================================
# JPA / HIBERNATE
# =========================================================

# Temporary for our first cloud deployment.
# Later we will replace this with Flyway migrations.
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}

spring.jpa.properties.hibernate.format_sql=false

spring.jpa.open-in-view=false


# =========================================================
# JWT
# =========================================================

# JWT_SECRET is supplied as an environment variable.